macro(set_local_qt_path QT_LOCAL_PATH)
    get_filename_component(QT_ABSOLUTE_PATH ${QT_LOCAL_PATH} ABSOLUTE)
    message(STATUS "## local QT path = ${QT_ABSOLUTE_PATH}")
    if(NOT EXISTS ${QT_ABSOLUTE_PATH})
        message(FATAL_ERROR "ERROR: QT path not found ${QT_LOCAL_PATH} ${QT_ABSOLUTE_PATH}")
    endif()
    if(APPLE)
        set(CMAKE_PREFIX_PATH ${QT_ABSOLUTE_PATH}/clang_64/lib/cmake)
        include_directories(${QT_ABSOLUTE_PATH}/clang_64/include)
    elseif(WIN32)
        set(CMAKE_PREFIX_PATH ${QT_ABSOLUTE_PATH}/msvc2017_64/lib/cmake)
        include_directories(${QT_ABSOLUTE_PATH}/msvc2017_64/include)
    endif()

endmacro()

function(find_include_dirs out)
    file(GLOB_RECURSE headers ${ARGN})
    foreach (path ${headers})
        get_filename_component(dir ${path} PATH)
        list(APPEND include_dirs ${dir})
    endforeach ()
    list(REMOVE_DUPLICATES include_dirs)
    set(${out} ${include_dirs} PARENT_SCOPE)
endfunction()